### ISSUE TITLE
Could you please explain the procedure of adding this bundle into my symfony project? thanks in advance! 

### ISSUE THREAD

**Issue by mani-nesan** [tkuska/dashboard#1]

**Comment by tkuska** [comment]
i've added some docs, i hope it will be extended in nex days :)

**Comment by mani-nesan** [comment]
I'm just a novice to this php & symfony stuff! When I render the dashboard.html.twig it shows an error "Variable "widgets" does not exist in dashboard.html.twig at line 33" !?

**Comment by tkuska** [comment]
did you pass your widgets list in your controller to your template?
$widgets = $this->get('tkuska_dashboard.widget_provider')->getMyWidgets();
return array('widgets' => $widgets);

or just add this in your routing.yml file
tkuska_dashboard:
    resource: "@TkuskaDashboardBundle/Controller/"
    type:     annotation
    prefix:   /
    options:
        expose: true

**Comment by mani-nesan** [comment]
thks! fixed it! but now I have some issues with CSS styles! What are the js/css links should be import in base.html.twig?

**Comment by tkuska** [comment]
bootstrap3, gridstack and responsiveCalendar for default widget calendar.
I will update docs today :)
