### ISSUE TITLE
Hi! When I add more than one widget. I can't move/close them? 

### ISSUE THREAD

**Issue by mani-nesan** [tkuska/dashboard#2]

**Comment by tkuska** [comment]
is your service alias the same as result of getType function in widget class?

**Comment by linganesan** [comment]
Yes! Console says "Uncaught TypeError: Cannot read property 'value' of undefined" in gridstack.js  in line 164!

**Comment by mani-nesan** [comment]
Fixed it! I'm really a stupid, just forget to import lodash.js. Sorry to being annoying. :)  Is there any way to update the dashboard_widgets table in the database with current configuration of the widgets placement? When I reload the dashboard page I like to have my new setup of dashboard.

**Comment by tkuska** [comment]
I work on saving dashboard state, so it ssould be done soon.

You are not annoying, i'm glad someone is so brave to use my undocumented bundle :)

**Comment by linganesan** [comment]
I'm really having a headache now! :P Is it possible to pass the JSON array to set new states of widgets in the update scenario according to their widget_type?

**Comment by tkuska** [comment]
i've added saving widgets state, when you move or resize widget, new position and size is saved in database
